baseURL: /
params:
  palette: green
  snipcart_api_key: 'ZjE3ZTU5YTQtYWNjOS00NjNkLTg2YjktYjU5MDFiZGNmNGY1NjM3NTQ0MjMwNjYyODA2ODUx '
  favicon: images/favicon.png
  logo_light: /images/Add a heading (1).png
  logo_dark: /images/wonderful-coriander.png
  hamburger_background_image: /images/leaf-light-grey.svg
  bg_image_primary: /images/header.jpg
  bg_image_primary_opacity: 60
  bg_image_secondary: /images/leaf-light-grey.svg
  bg_image_product: /images/leaf.svg
  main_menu:
    - type: action
      title: Store
      url: /store
      style: link
    - type: action
      title: About
      url: /about
      style: link
    - type: action
      title: FAQ
      url: /faq
      style: link
  footer_text: Copyright 2021 Getawebsite Inc. All rights reserved.
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
title: GETAWEBSITE
